nameReference:
- kind: Secret
  fieldSpecs:
  - path: spec/cloudCredentialsRef/secretName
    kind: Network
  - path: spec/cloudCredentialsRef/secretName
    kind: Subnet
  - path: spec/cloudCredentialsRef/secretName
    kind: Router
  - path: spec/cloudCredentialsRef/secretName
    kind: Port
  - path: spec/cloudCredentialsRef/secretName
    kind: Flavor
  - path: spec/cloudCredentialsRef/secretName
    kind: SecurityGroup
  - path: spec/cloudCredentialsRef/secretName
    kind: Image
  - path: spec/cloudCredentialsRef/secretName
    kind: Server
  - path: spec/resource/userData/secretRef
    kind: Server

- kind: Network
  fieldSpecs:
  - path: spec/networkRef
    kind: Subnet
  - path: spec/resource/externalGateways/networkRef
    kind: Router
  - path: spec/networkRef
    kind: Port

- kind: SecurityGroup
  fieldSpecs:
  - path: spec/resource/securityGroupRefs[]
    kind: Port

- kind: Subnet
  fieldSpecs:
  - path: spec/resource/addresses[]/subnetRef
    kind: Port

- kind: Router
  fieldSpecs:
  - path: spec/resource/routerRef
    kind: Subnet

- kind: Image
  fieldSpecs:
  - path: spec/resource/imageRef
    kind: Server

- kind: Flavor
  fieldSpecs:
  - path: spec/resource/flavorRef
    kind: Server

- kind: Port
  fieldSpecs:
  - path: spec/resource/ports[]/portRef
    kind: Server
