---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Server
metadata:
  name: bastion
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    imageRef: cirros
    flavorRef: small
    ports:
    - portRef: bastion-external
    - portRef: bastion-internal
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Port
metadata:
  name: bastion-external
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  networkRef: external
  resource:
    securityGroupRefs:
    - allow-ssh
    - default
    addresses:
    - subnetRef: external-ipv4
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Port
metadata:
  name: bastion-internal
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  networkRef: internal
  resource:
    securityGroupRefs:
    - allow-ssh
    - default
    addresses:
    - subnetRef: internal-ipv4
