---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: cirros
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    content:
      diskFormat: qcow2
      download:
        url: https://download.cirros-cloud.net/0.6.3/cirros-0.6.3-x86_64-disk.img
        hash:
          algorithm: sha256
          value: 7d6355852aeb6dbcd191bcda7cd74f1536cfe5cbf8a10495a7283a8396e4b75b
