---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Network
metadata:
  name: internal
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    description: An internal network
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: internal-ipv4
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  networkRef: internal
  resource:
    description: Deployment's internal IPv4 subnet
    ipVersion: 4
    cidr: 192.168.0.0/24
    routerRef: gateway
