apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: orcdemo-

components:
- ../../components/kustomizeconfig

resources:
- bastion-server.yaml
- image.yaml
- internal-network.yaml
- private-server.yaml
- router.yaml
- securitygroup.yaml
