---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Server
metadata:
  name: private
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    imageRef: cirros
    flavorRef: small
    ports:
    - portRef: private-internal
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Port
metadata:
  name: private-internal
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  networkRef: internal
  resource:
    securityGroupRefs:
    - allow-ssh
    - default
    addresses:
    - subnetRef: internal-ipv4
