apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Router
metadata:
  name: gateway
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    description: Gateway router for internal network
    externalGateways:
    - networkRef: external
