---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: SecurityGroup
metadata:
  name: allow-ssh
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    stateful: true
    rules:
    - direction: ingress
      protocol: tcp
      portRange:
        min: 22
        max: 22
      ethertype: IPv4
